### ISSUE TITLE
Extensions are not detected consistently 

### ISSUE THREAD

**Issue by Geo25rey** [airgap-it/beacon-sdk#259] opened 2021-08-24 17:58 UTC
**Describe the bug (current behavior)**

When initializing the Beacon SDK with as a `DappClient`, then starting a pairing request directly afterwards, extensions, such as Temple Wallet and Spire, are not always detected when they are installed. 

This behavior is highly inconsistent. Sometimes the extensions are not detected even after reload the page many times. Sometimes it is only Spire that is detected (10%-25% of the time). Sometimes both are detected (50%-80% of the time).

Below are my limited statistics from manual testing (~100-200 times)
No extensions detected: 10%-25% of the time
Only Spire detected: 10%-25% of the time
Both Spire and Temple Wallet detected: 50%-80% of the time

Others have experienced more consistent extension detection on various platforms, but most only have Temple Wallet installed.

**To Reproduce**

Run the following code with both Spire and Temple Wallet installed (or just Temple on Firefox) and refresh until 1 or both are not detected. This is speculation, but having DevTools opened seems to increase the failure rate. As a debug mechanism, I have added an message event listener to print out all the events to see when the "ping" and "pong" events happen.

Beacon SDK specific:
```javascript
import { DAppClient } from "@airgap/beacon-sdk";

const dAppClient = new DAppClient({ name: "Beacon Docs" });
const permissions = await dAppClient.requestPermissions();
```

Benchmarking Tool:
```javascript
const EXTENSIONS_COUNT = 2; // how many extension you have installed (Spire and Temple for me)
const start = Date.now();
window.addEventListener('load', function () {
  const load = Date.now();
  let pongs = 0;
  window.addEventListener("message", function (e) {
    console.log(e.data);
    if (e.data.payload === 'pong') { // count pongs
      pongs++;
    }
    if (pongs === EXTENSIONS_COUNT) { // all pongs received 
      const now = Date.now()
      console.log('start -> load', (load - start) / 1000);
      console.log('load -> pongs', (now - load) / 1000);
      console.log('start -> pongs', (now - start) / 1000);
    }
  });
  window.postMessage({ target: "toExtension", payload: "ping" }); // only need 1 ping for the extensions
});
```

**Expected (correct) behavior**

Extensions should be detected regardless of timing. As mentioned in #137, it is probably time to alter the method or architecture  for extension detection done [here](https://github.com/airgap-it/beacon-sdk/blob/f7311217e58ddbe9d14553c85d318c09fad8a7cc/src/transports/PostMessageTransport.ts#L63L105). More specifically, the promise their probably should be a promise which handles the message event handler. Instead maybe the event handler should always be active and should update the internal state of `DAppClient` which updates the permission request modal.

**Environment**

- Device: multiple laptops and desktops of various speeds
- OS: Windows, Linux, and Mac
- Browser: Chrome and Firefox

**Comment by burk3** [comment] 2021-09-01 17:09
@AndreasGassmann I'm going to copy-paste our chat into here so it doesn't get lost. 

@AndreasGassmann : 
> Without going into detail, is it actually necessary to show the pairing alert on pageload? Usually having users initiate the flow with a button press will give you better UX and would also work around your problem :).

@burk3 :
> We don't show on page load, we show when the user clicks a button to bring up the beacon modal. The code in the issue is purely for easy reproduction of the bug. We initially created the beacon object and attached the perm request to a button, but ended up trying to delay the object creation until the button press to see if the extension would have a better chance of being awake enough to respond within 1sec. The same thing still happens in both cases.

**Comment by burk3** [comment] 2021-09-01 17:46
@AndreasGassmann, fwiw, we're looking to help solve this issue for every user of beacon rather than just finding a fix for ourselves. We have reproduced this issue on HEN and other sites in addition to our own. We're confident we're using it correctly and that we've tried adjusting our usage of it in ways that could get around these issues. We can provide examples that repro on button click if you really don't believe us, but you'll still need a slow computer and patience to achieve repro.

**Comment by pascuin** [comment] 2021-09-01 18:00
Hey sorry for the late reply on our end on this. 

As @AndreasGassmann is currently not available @jsamol is looking into this, we should have more details tomorrow.

**Comment by Geo25rey** [comment] 2021-09-01 22:56
Thanks @pascuin

**Comment by AndreasGassmann** [comment] 2021-09-02 23:22
We were finally able to look into this, but we don't really know what's going on because we haven't been able to reproduce this.

Maybe you have looked at how the flow is, but just so everyone is on the same page, here is what happens:

1. When the beacon code is executed (during page load), a ping is sent to indicate to extensions that they have to send a pong.
2. During the window of 1000ms, every extension that sent a pong will be registered.
3. When the DAppClient is created and the pairing alert is displayed, it will take all the extensions into considerations that have been registered in the first 1000ms after the page was loaded. It also means that we always wait a minimum of 1000ms before displaying the pairing alert.

So what this means is that in your case, for whatever reason, the pong is not received within 1 second of the ping being sent. If this is actually the case, then I would suggest trying to find out where that delay comes from. Because no matter what improvements we make to the SDK, if the pong takes 1, 5 or 10 seconds, it is not possible to give a consistent and good user experience anyway.

One behavior that doesn't really make sense in the current flow is that there is a hard limit of 1s to listen for extensions. We removed this limit and pushed beacon-sdk v2.3.2-beta.0. Could you give that a try and let us know if it improves the situation?

The next step from our side will be to make the pairing alert list "dynamic" so it will update even if a pong is received while the alert is open.

But as I mentioned, a pong that takes more than 1s is probably not normal and I don't think this is something that most people are affected by. During testing, I noticed that the dev-tools can make the pong slower, but also when there is more load on the CPU. Maybe the number of extensions affects it as well.

Do you have any data on how long the pongs take in your case? Can you also confirm that it generally takes considerably longer on older computers?

**Comment by jsamol** [comment] 2021-09-03 14:08
> The next step from our side will be to make the pairing alert list "dynamic" so it will update even if a pong is received while the alert is open.

We've just pushed a new beta `beacon-sdk v2.3.2-beta.1` that comes with this change. If the previous fix doesn't solve your issue, try with that one.

**Comment by Geo25rey** [comment] 2021-09-03 23:15
@jsamol I left a review on your PR https://github.com/airgap-it/beacon-sdk/pull/262#pullrequestreview-746506346

**Comment by AndreasGassmann** [comment] 2021-09-03 23:18
@Geo25rey Did you test `beta.0` or `beta.1`? I'm still curious how long the pong actually takes in your case, because it has to be more than a second to be affected by the latest changes.

**Comment by Geo25rey** [comment] 2021-09-06 12:08
> Did you test beta.0 or beta.1?
beta.1

> I'm still curious how long the pong actually takes in your case, because it has to be more than a second to be affected by the latest changes.

In my case, the pong messages typically took less than 100ms to respond. So, I'm not sure if it was the timeout or some bad logic somewhere. Minimally @jsamol's PR seems to help a lot and I haven't been able to reproduce the bug. 

@burk3 and I are going to do a release on Thursday and can have our ~60 beta testers try it out. Would you recommend using the beta.1 version or do you plan on having this released by then?

**Comment by jsamol** [comment] 2021-09-08 15:47
> Would you recommend using the beta.1 version or do you plan on having this released by then?

@Geo25rey we're actually planning to make a release that will include this change tomorrow, unless there's something unexpectedly blocking us.

**Comment by Geo25rey** [comment] 2021-09-08 15:56
> > Would you recommend using the beta.1 version or do you plan on having this released by then?
> 
> @Geo25rey we're actually planning to make a release that will include this change tomorrow, unless there's something unexpectedly blocking us.

That's perfect. Thank you.

**Comment by Geo25rey** [comment] 2021-09-10 16:07
@jsamol @AndreasGassmann How's the release going?

**Comment by AndreasGassmann** [comment] 2021-09-10 16:11
It should be ready shortly, a few hours max.

**Comment by AndreasGassmann** [comment] 2021-09-10 20:12
@Geo25rey We just released 2.3.2.

**Comment by Geo25rey** [comment] 2021-09-10 21:26
Thanks a lot @AndreasGassmann. We are going to test this with users within the next 2 weeks and this should hopefully confirm that this issue is resolved.

**Comment by magician11** [comment] 2021-09-21 02:30
The latest update looks like it fixed it.

In development, I was rarely able to see the temple wallet as an option in the list of wallets to connect to. It kept saying the temple wallet was not installed, when it definitely is.

However, on building and deploying the app, the connection to the temple wallet works fine. So it seems that 1s ping pong time mentioned above was being exceeded in development I guess.

Either way, the latest update seems to have fixed it. I can now consistently connect to the temple wallet in development. Thanks.

**Comment by AndreasGassmann** [comment] 2021-09-21 03:46
> So it seems that 1s ping pong time mentioned above was being exceeded in development I guess

It would be interesting to know why that is. I have never consistently experienced this issue, neither in production, nor in development environments. Next week I'll try to run the whole browser/extension in a VM and see if the performance decrease has anything to do with it.

I will close this issue now that it has been resolved.

**Closed by AndreasGassmann** 2021-09-21 03:46 UTC
Labels: bug

**Comment by my8bit** [comment] 2022-08-04 18:19
Same issue here with private IP range as well.

**Comment by AndreasGassmann** [comment] 2022-08-05 09:56
Make sure the page is served over https.

**Comment by Geo25rey** [comment] 2022-08-05 10:16
@AndreasGassmann The fact that a local address is being used makes it a secure context.

Quote from MDN:
```
Locally-delivered resources such as those with http://127.0.0.1 URLs, http://localhost and http://*.localhost URLs (e.g. http://dev.whatever.localhost/), and file:// URLs are also considered to have been delivered securely.
```

See more info [here](https://developer.mozilla.org/en-US/docs/Web/Security/Secure_Contexts#feature_detection).

**Comment by AndreasGassmann** [comment] 2022-08-08 09:44
@my8bit was accessing it over 192.168... which does not seem to be a secure context. And @karimkawambwa has `local.host` in their URL, which I have never seen, so it might also not be a secure context.

**Comment by karimkawambwa** [comment] 2022-08-08 14:12
> Make sure the page is served over https.

@AndreasGassmann thanks for responding to this.

I haven't tested if http://localhost will work but I use a custom hostname http://local.host to support cookies when developing on my machine. 

I'll follow these two processes to use local https for the custom hostname
- https://web.dev/when-to-use-local-https/
- https://web.dev/how-to-use-local-https/
