### ISSUE TITLE
Batch operation payload taking too long to be passed to beacon wallets

### ISSUE THREAD

**Issue by LMilfont** [airgap-it/beacon-sdk#469] opened 2023-04-11 22:36 UTC
**Describe the bug (current behavior)**
When sending a batch operation with batch.send() method (from Taquito, that uses @airGap/DappClient.ts) depending on the size of the payload, it takes a long time until the beacon wallet receives the batch. Apparently it's a quadratic relation regarding number of transactions inside the batch. 

**To Reproduce**
1. Create a Javascript array with opKind.Transaction elements.
2. Call the batch.send() method with the payload.

**Expected (correct) behavior**
Sending the payload to the wallet should be much faster.

**Screenshots and/or logs**
```
Creation of Array with 441 elements took 8ms        (this occurs in my dApp) 
0ms init done DAppClient.ts:1399:12
10914ms sending DAppClient.ts:1447:12
10945ms sent DAppClient.ts:1466:12
18199ms acknowledge DAppClient.ts:263:18

Creation of Array with 1005 elements took 26ms   (this occurs in my dApp)
1ms init done DAppClient.ts:1399:12
56961ms sending DAppClient.ts:1447:12        (here is the problem).
57004ms sent

Creation of Array with 2020 elements took 35ms   (this occurs in my dApp)
0ms init done DAppClient.ts:1399:12
229321ms sending DAppClient.ts:1447:12    (with around 2000 elements, it hangs browser - look at the time taken)
229386ms sent
``` 

**Environment**

- Device: Computer
 - OS: Windows
 - Browser: Firefox or Chrome

**Additional context**
It maybe something that could be optimized on the code, or maybe on the moment of sending
payload to the wallet (is it a post? Maybe configuring http header to Accept-Encoding: gzip
Accept-Encoding: compress, I don;t know).

**Comment by IsaccoSordo** [comment] 2023-08-24 06:59
Hi @LMilfont,
I think this issue is somewhat related to #467, as you can see the problem is not beacon per se but a mix of factors.
We don't have ownership on Taquito, so we have tested using the DApp client directly and no major performance issues were encountered.
For now I close the issue, in case you have more infos please feel free to reopen it again.

**Closed by IsaccoSordo** 2023-08-24 06:59 UTC
Labels: bug
