### ISSUE TITLE
TypeError: BeaconEvent is undefined in Vite v5

### ISSUE THREAD

**Issue by BearCooder** [airgap-it/beacon-sdk#668] opened 2023-11-20 16:00 UTC
**Describe the bug (current behavior)**
I have a working dapp. The setup I use is React with Vite v4 together with taquito and Beacon.

Now after I updated Vite to their latest release [v5](https://vitejs.dev/blog/announcing-vite5) I get always a blank page and the error in the browser console:
TypeError: BeaconEvent is undefined.
![grafik](https://github.com/airgap-it/beacon-sdk/assets/104575503/0ad39451-a971-4635-9098-734e380c4f85)

Now when I click to show me source it is something not working in the beacon package I guess:
![grafik](https://github.com/airgap-it/beacon-sdk/assets/104575503/6f9fb76b-10ce-416f-a3a6-de0715688792)

I cant even really fix it as I get no errors in my console in WSL when I start to run it locally. No errors, just a blank page appears and then a look in the browser console shows me this.

I use WSL with node v 20.9.0 and the latest taquito and beacon versions.

**Comment by IsaccoSordo** [comment] 2023-11-21 09:36
Hi @BearCooder,
thanks for your report.
I don't know your specific vite setup, [here](https://stackblitz.com/edit/vitejs-vite-kkslry?file=src%2FApp.tsx,vite.config.ts) I have created a simple beacon playground with vite 5 and react.
Please tell me if you manage to also replicate your issue with the playground

**Comment by BearCooder** [comment] 2023-11-21 17:51
Hello @IsaccoSordo thank you for the quick answer.

I can provide you the whole template that my project is based on.
Here: https://github.com/dvkam/Tezos-Template

Please clone it and install dependencies and try to run, it will work. But when you delete node modules and just change the Vite version to v5 in package json and install again. Then you will get the problem I described. A blank page and in browser console the error from above..

Even when beacon and taquito is updated to the latest version with Vite v5 I get the same :(

**Comment by IsaccoSordo** [comment] 2023-11-22 10:33
Hi @BearCooder,
thanks for sharing your code.
I see now, the problem is not vite per se but the fact that you most likely need to run `npm i --lecacy-peer-deps` or `npm i -f`
Using those flags might introduce unintended consequences, as the flags allow for looser constraints on dependencies.
In your specific case what you can do if you still want to use vite@5 is to change the import, inside **Wallet.ts** , from `import { NetworkType } from "@airgap/beacon-sdk";` to `import { NetworkType } from "@airgap/beacon-dapp";`
Please let me know if this solves your issue.

**Comment by BearCooder** [comment] 2023-11-23 12:12
Wow, changing the import from `import { NetworkType } from "@airgap/beacon-sdk";` to` import { NetworkType } from "@airgap/beacon-dapp";` solved the issue! Thank you very much!

Can you please explain what the difference here is and why the old import worked fine in Vite v4 and now not anymore in Vite v5?

**Comment by IsaccoSordo** [comment] 2023-11-23 12:44
I'm glad it worked out for you, I'm closing the issue.
If you need more details about `npm i --legacy-peer-deps` I found this nice StackOverflow issue which explains it in details: [what-does-npm-install-legacy-peer-deps-do](https://stackoverflow.com/questions/66239691/what-does-npm-install-legacy-peer-deps-do-exactly-when-is-it-recommended-wh)

**Closed by IsaccoSordo** 2023-11-23 12:44 UTC
Labels: bug, waiting for feedback

**Comment by BearCooder** [comment] 2023-11-23 18:32
Thank you @IsaccoSordo but one last question. I just changed the import and did not run `npm i --lecacy-peer-deps`. I read the linked Stackoverflow issue but I do not can find how this is connected with it? I just changed the import like you said, nothing else?

**Comment by IsaccoSordo** [comment] 2024-03-25 16:09
Hi @BearCoder,
I apologize for the significant delay in my response – I've been tied up with other duties. Regarding the issue you raised, I've been investigating it alongside my other tasks. It took some time, but I've identified the root cause.
The issue appears to be with Vite’s TypeScript transpilation, specifically in how we bundle our submodules in Beacon. For instance, in beacon-dapp's index.ts, we export necessary submodules like beacon-core and beacon-types. However, this is also true for beacon-sdk, which exports the beacon-app submodule. It seems recent changes in Vite's transpilation process now create a circular dependency.
If you want you can build Beacon locally by branching out from fix/clashing_types and you’ll see that the issue no longer appears.
Although we might not proceed with merging [PR#738](https://github.com/airgap-it/beacon-sdk/pull/738), it's currently open for internal discussion.
Thanks a lot for opening this issue.
