### ISSUE TITLE
Duplicate wc2 event listeners

### ISSUE THREAD

**Issue by klassare** [airgap-it/beacon-sdk#758] opened 2024-04-15 13:28 UTC
**Describe the bug (current behavior)**
Duplicate (or more) event listeners are set up when a dapp is opened in more than one tab. Resulting in ACTIVE_ACCOUNT_SET being emitted multiple times.

**To Reproduce**
1. Go to the example dapp
2. Connect with Kukai using the wc2 transport and approve the permission request
3. open the example dapp in a 2th tab
4. do an account change from the wallet

**Expected (correct) behavior**
ACTIVE_ACCOUNT_SET should only be emitted once

**Additional context**
Subscriptions can be set up twice in [refreshState()](https://github.com/airgap-it/beacon-sdk/blob/8452a04057e308e40c9f01c821490fca36bef9f0/packages/beacon-transport-walletconnect/src/communication-client/WalletConnectCommunicationClient.ts#L164-L180). [Directly](https://github.com/airgap-it/beacon-sdk/blob/8452a04057e308e40c9f01c821490fca36bef9f0/packages/beacon-transport-walletconnect/src/communication-client/WalletConnectCommunicationClient.ts#L174) and [indirectly](https://github.com/airgap-it/beacon-sdk/blob/8452a04057e308e40c9f01c821490fca36bef9f0/packages/beacon-transport-walletconnect/src/communication-client/WalletConnectCommunicationClient.ts#L1321) via [getSignClient()](https://github.com/airgap-it/beacon-sdk/blob/8452a04057e308e40c9f01c821490fca36bef9f0/packages/beacon-transport-walletconnect/src/communication-client/WalletConnectCommunicationClient.ts#L1317-L1336)

**Comment by IsaccoSordo** [comment] 2024-04-16 13:21
Hi @klassare,
The issue was caused by our cleanup logic.
Because of `refreshState` some uncleared subscriptions were triggered again upon receiving an event.

**Comment by IsaccoSordo** [comment] 2024-04-22 11:22
Hi @klassare,
the cleanup should now be correctly handled.
You can see the changes in #764

**Comment by IsaccoSordo** [comment] 2024-05-17 07:05
The fix has been included in [v4.2.2](https://github.com/airgap-it/beacon-sdk/releases/tag/v4.2.2)

**Closed by IsaccoSordo** 2024-05-17 07:05 UTC
Labels: bug
