### ISSUE TITLE
Permission request not possible after pairing has expired

### ISSUE THREAD

**Issue by klassare** [airgap-it/beacon-sdk#620] opened 2023-10-18 13:07 UTC
**Describe the bug (current behavior)**
It's not possible to send a permission request without a pairing

**To Reproduce**
1. Par with Kukai from the example dapp
2. Remove the pairing (or let it expire) from Kukai
3. Try to send a permission request

**Expected (correct) behavior**
Allow permission request to be sent when a session exist, but no pairing. Do a session update instead of creating a new session.

**Environment**

- Device: MacBook Pro
- OS: macOS Sonoma
- Browser: Chrome

**Additional context**
Branch: feat/transport-kukai-wc2

**Comment by IsaccoSordo** [comment] 2023-11-06 17:15
Hi @klassare,
to trigger this flow we implemented a new optional method `tezos_requestNewAccount` that needs to be approved.
We are also sending, through params, the current messageId (as ` id: this.currentMessageId!`)
Relevant lines of code: [WalletConnectCommunicationClient.ts#L198-#L219](https://github.com/airgap-it/beacon-sdk/blob/feat/transport-kukai-wc2/packages/beacon-transport-walletconnect/src/communication-client/WalletConnectCommunicationClient.ts#L198-#L219)

**Comment by klassare** [comment] 2023-11-08 18:18
Toast notification is unresponsive to the session update.

**Comment by AndreasGassmann** [comment] 2023-11-08 20:07
I think I accidentally cleared the session instead of the pairing in step 2, which is why I thought that this was fixed, sorry about that.

I can confirm that the UI doesn't behave correctly. It does something, but instead of showing the "permission granted" UI, it shows the "Awaiting response" message again.

Did you add the acknowledge message mentioned in this ticket now? https://github.com/airgap-it/beacon-sdk/issues/645 Because I think that wasn't there before IIRC. We may have an error in the logic handling the acknowledge message.

**Comment by AndreasGassmann** [comment] 2023-11-09 11:50
@klassare we have a fix in the works in https://github.com/airgap-it/beacon-sdk/pull/653 and are currently testing it.

We noticed that the new "Change Session Account" alert on Kukai has a different behaviour compared to the other alerts:
1. It is only showing up on one tab, not all of them
2. There is no indicator in the browser tab icon that the user is prompted to do something.

There is the issue that an "abort" of the "Change Session Account" alert doesn't do anything. Here https://github.com/airgap-it/beacon-sdk/issues/646#issuecomment-1798672900 you suggested that we could represent the rejection as state change A => A. In this case, this could work. So we could check the current active account and if it's the same, we simply hide the UI (I think no error would be the best UX). Do you agree with this?

**Comment by klassare** [comment] 2023-11-09 13:31
I'm aware that it needs some cleanup on the Kukai side. Just wanted to make it possible to test the flow completely on your end first.

**Comment by AndreasGassmann** [comment] 2023-11-09 13:58
We were able to test it now and merged it back to the main branch, thanks.

We still have to decide on how we handle the case where the user cancels the request.

**Comment by IsaccoSordo** [comment] 2024-02-08 08:46
This flow has been discarded. Possible future consideration.

**Closed as completed by IsaccoSordo** 2024-02-08 08:46 UTC
Labels: bug, wontfix, future consideration, testing
