### ISSUE TITLE
Temple Wallet popup never comes on an originate call with big payload and the tab becomes unresponsive for a bit

### ISSUE THREAD

**Issue by Man-Jain** [airgap-it/beacon-sdk#467] opened 2023-04-04 13:47 UTC
**Describe the bug (current behavior)**
The Temple Wallet popup never comes on an originate call with big payload and the dapp page becomes unresponsive for a bit. 

**To Reproduce**
In our case the when the contract origination request is sent with Code size - 122KB and Storage Size 24 Kb. 

**Expected (correct) behavior**
The popup to confirm or reject the transaction should show up.

**Screenshots and/or logs**
It says awaiting, but the confirmation never shows up
<img width="586" alt="Screenshot 2023-04-04 at 7 08 15 PM" src="https://user-images.githubusercontent.com/12700384/229812279-f483f06c-ffa2-4fd6-b474-9ecb28b60d4b.png">

Some More context - 
This is not definitive, sometimes the confirmation popup does come up but it's fewer than when it doesn't

**Comment by LMilfont** [comment] 2023-04-11 22:43
I have a similar issue, regardind passing 2000+ transactions inside a batch operation. Hangs the browser. It is taking too long to the payload to arrive at the beacon wallet, for some reason. The bigger the payload, the worse. It might be something that could be optimized on the algorithm or compressed with http headers like Accept-Encoding: gzip / Accept-Encoding: compress, if it's a post. I don't know.

**Comment by IsaccoSordo** [comment] 2023-08-15 12:54
Hi @Man-Jain, I'm taking over here.
So I tried to replicate the issue you are facing, forking for instance [BetterCallDev](https://better-call.dev/mainnet/KT18x66448Gt3kYYkfvx4Cg2dP9cRPfjQwVv/fork) to the ghostnet  slows down the app a lot.
This however is not an issue directly related to beacon.
As a test, I tried to replicate the BetterCallDev issue using the beacon playground and connecting to a Temple wallet in order to isolate the call from anything else.
No major performance issues were encountered and the toast appears as expected.
I don't know your specific environment but the cause might be a mix of request size and network latency.
For now I close the issue, but feel free to reopen it if you have more infos on this topic.

**Closed by IsaccoSordo** 2023-08-15 12:54 UTC
Labels: bug
